<?php

require_once 'vendor/autoload.php';
use opdracht1\House;

print ("house 1");
print ("<br>");
$house1 = new House();
$house1->setNumberOfFloors(3);
print $house1->getNumberOfFloors();
print ("<br>");
$house1->setNumberOfRooms(7);
print $house1->getNumberOfRooms();
print ("<br>");
$house1->setWidth(5.5);
print $house1->getWidth();
print ("<br>");
$house1->setDepth(11);
print $house1->getDepth();
print ("<br>");
$house1->setHeight(7.5);
print $house1->getHeight();
print ("<br>");
$house1->setPrice(44.24);
print $house1->getPrice();
print ("<br>");
print ("<br>");

print ("house 2");
print ("<br>");
$house2 = new House();
$house2->setNumberOfFloors(1);
print $house2->getNumberOfFloors();
print ("<br>");
$house2->setNumberOfRooms(8);
print $house2->getNumberOfRooms();
print ("<br>");
$house2->setWidth(10);
print $house2->getWidth();
print ("<br>");
$house2->setDepth(10);
print $house2->getDepth();
print ("<br>");
$house2->setHeight(2.60);
print $house2->getHeight();
print ("<br>");
$house2->setPrice(44.24);
print $house2->getPrice();
print ("<br>");
print ("<br>");

print ("house 3");
print ("<br>");
$house3 = new House();
$house3->setNumberOfFloors(2);
print $house3->getNumberOfFloors();
print ("<br>");
$house3->setNumberOfRooms(6);
print $house3->getNumberOfRooms();
print ("<br>");
$house3->setWidth(10);
print $house3->getWidth();
print ("<br>");
$house3->setDepth(11);
print $house3->getDepth();
print ("<br>");
$house3->setHeight(5);
print $house3->getHeight();
print ("<br>");
$house3->setPrice(44.24);
print $house3->getPrice();
